language: php

php:
  - 8.0
  - 7.4
  - 7.3
  - 7.2
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
  - php: hhvm
  - php: nightly
  - php: 8.0

sudo: false

install:
  - travis_retry composer update --no-progress --prefer-dist --profile

script:
  - composer test

  
